# Generated by Django 5.0.3 on 2024-04-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Doctor',
        ),
    ]
